### ISSUE TITLE
Applications going off screen

### ISSUE THREAD

**Issue by Jbteam2** [teamswiftos/swiftos#3]
![SwiftOS  Running  - Oracle VM VirtualBox 26_08_2023 22_13_04](https://github.com/teamswiftos/swiftos/assets/109432716/62056cd0-00ef-43e4-94be-6edc34133bdd)
This was ran inside a VirtualBox and as seen the top of the application glitched above the controls this makes it unable to close/minamize/fullscreen the application or move it around.

**Comment by natesworksog** [comment]
I already know how to fix it will be fixed in 0.1.2 
(Tommorow)
